// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6FpVQAnUSA1VNbtSSDYTw-0GKDdeNX2U',
    appId: '1:150226999462:web:9e91485a2373f747803c67',
    messagingSenderId: '150226999462',
    projectId: 'lingayen-lto',
    authDomain: 'lingayen-lto.firebaseapp.com',
    storageBucket: 'lingayen-lto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATY5vx4rfAREgBIzDhx-BceEE4yfo31lU',
    appId: '1:150226999462:android:b1dba8d3e45a6cb1803c67',
    messagingSenderId: '150226999462',
    projectId: 'lingayen-lto',
    storageBucket: 'lingayen-lto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADBqRwyPWTovlKkp7E9WZgHVdAd2x_W_g',
    appId: '1:150226999462:ios:302f7e493cd24cfc803c67',
    messagingSenderId: '150226999462',
    projectId: 'lingayen-lto',
    storageBucket: 'lingayen-lto.firebasestorage.app',
    iosBundleId: 'com.example.enforcerAutoFine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADBqRwyPWTovlKkp7E9WZgHVdAd2x_W_g',
    appId: '1:150226999462:ios:302f7e493cd24cfc803c67',
    messagingSenderId: '150226999462',
    projectId: 'lingayen-lto',
    storageBucket: 'lingayen-lto.firebasestorage.app',
    iosBundleId: 'com.example.enforcerAutoFine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6FpVQAnUSA1VNbtSSDYTw-0GKDdeNX2U',
    appId: '1:150226999462:web:545b9bc452157485803c67',
    messagingSenderId: '150226999462',
    projectId: 'lingayen-lto',
    authDomain: 'lingayen-lto.firebaseapp.com',
    storageBucket: 'lingayen-lto.firebasestorage.app',
  );
}
